version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached

  neo4j:
    image: neo4j:5.15.0
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - neo4j-data:/data
      - neo4j-plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: "[\"apoc\", \"n10s\", \"graph-data-science\"]"

volumes:
  neo4j-data:
  neo4j-plugins:
