version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached

  neo4j:
    image: neo4j:5.15.0
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - neo4j-data:/data
      - neo4j-plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: "[\"apoc\", \"n10s\", \"graph-data-science\"]"

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    network_mode: service:app

  zipkin:
    image: openzipkin/zipkin:latest
    restart: unless-stopped
    network_mode: service:app

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: unless-stopped
    network_mode: service:app
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

volumes:
  neo4j-data:
  neo4j-plugins:
