/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cfTRMQdCr74
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useMemo } from "react"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Card, CardContent } from "@/components/ui/card"

export function SearchTeacher() {
  const [searchQuery, setSearchQuery] = useState("")
  const [teachers, setTeachers] = useState([
    {
      id: 1,
      name: "Dr. Emily Wilkins",
      department: "Computer Science",
      subjects: ["Algorithms", "Data Structures", "Software Engineering"],
      bio: "Dr. Emily Wilkins is an Associate Professor of Computer Science at the University of Techville. She received her Ph.D. in Computer Science from the Massachusetts Institute of Technology and has been teaching at the university for the past 8 years. Her research interests include artificial intelligence, machine learning, and natural language processing.",
      email: "emily.wilkins@techville.edu",
      phone: "555-1234",
      courses: ["CS101 - Introduction to Computer Science", "CS301 - Advanced Algorithms", "CS401 - Machine Learning"],
    },
    {
      id: 2,
      name: "Dr. Michael Johnson",
      department: "Biology",
      subjects: ["Genetics", "Ecology", "Microbiology"],
      bio: "Dr. Michael Johnson is a Professor of Biology at the University of Techville. He received his Ph.D. in Molecular Biology from the University of California, Berkeley, and has been teaching at the university for the past 15 years. His research focuses on the genetic basis of plant adaptations to environmental stresses.",
      email: "michael.johnson@techville.edu",
      phone: "555-5678",
      courses: ["BIO101 - Introduction to Biology", "BIO301 - Genetics", "BIO401 - Ecology"],
    },
    {
      id: 3,
      name: "Dr. Sarah Lee",
      department: "English",
      subjects: ["American Literature", "Creative Writing", "Composition"],
      bio: "Dr. Sarah Lee is an Assistant Professor of English at the University of Techville. She received her Ph.D. in English Literature from the University of Oxford and has been teaching at the university for the past 5 years. Her research interests include 20th-century American literature and the intersection of literature and social justice.",
      email: "sarah.lee@techville.edu",
      phone: "555-9012",
      courses: ["ENG101 - Composition I", "ENG301 - American Literature", "ENG401 - Creative Writing"],
    },
    {
      id: 4,
      name: "Dr. Liam Nguyen",
      department: "Mathematics",
      subjects: ["Calculus", "Linear Algebra", "Discrete Mathematics"],
      bio: "Dr. Liam Nguyen is an Associate Professor of Mathematics at the University of Techville. He received his Ph.D. in Mathematics from the University of Cambridge and has been teaching at the university for the past 10 years. His research focuses on the applications of mathematics in computer science and engineering.",
      email: "liam.nguyen@techville.edu",
      phone: "555-3456",
      courses: ["MATH101 - Calculus I", "MATH301 - Linear Algebra", "MATH401 - Discrete Mathematics"],
    },
  ])
  const filteredTeachers = useMemo(() => {
    return teachers.filter((teacher) => {
      const searchValue = searchQuery.toLowerCase()
      return (
        teacher.name.toLowerCase().includes(searchValue) ||
        teacher.department.toLowerCase().includes(searchValue) ||
        teacher.subjects.some((subject) => subject.toLowerCase().includes(searchValue))
      )
    })
  }, [searchQuery, teachers])
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="mb-8">
        <Input
          placeholder="Search for teachers..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="bg-white dark:bg-gray-950"
        />
      </div>
      <div className="grid gap-6">
        {filteredTeachers.map((teacher) => (
          <Link key={teacher.id} href="#" prefetch={false}>
            <Card className="group">
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold">{teacher.name}</h3>
                <p className="text-muted-foreground">{teacher.department}</p>
                <div className="mt-2 flex flex-wrap gap-2">
                  {teacher.subjects.map((subject, index) => (
                    <span key={index} className="rounded-full bg-muted px-3 py-1 text-xs font-medium">
                      {subject}
                    </span>
                  ))}
                </div>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  )
}
